### ISSUE TITLE
Infinite unknown post messages

### ISSUE THREAD

**Issue by sefeng211** [firefox-devtools/firefox-profiler-for-chrome#3]
I am running Chromium on Linux with the following UA 
`Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36` 

STR:
   * Open google.com
   * start the profiler 
   * search "123"
   * stops the profiler

AR:
   The profiler stucks at that `Importing the profile directly from ⁨Firefox⁩…` page

By checking the developer console, I see something like this goes indefinitely 
```
Received postMessage {name: 'ready:request'}
main.af6d8eda1550bb1b4419.bundle.js:95 Unknown post message {name: 'ready:request'}
main.af6d8eda1550bb1b4419.bundle.js:95 Received postMessage {name: 'ready:request'}
main.af6d8eda1550bb1b4419.bundle.js:95 Unknown post message {name: 'ready:request'}
main.af6d8eda1550bb1b4419.bundle.js:95 Received postMessage {name: 'ready:request'}
main.af6d8eda1550bb1b4419.bundle.js:95 Unknown post message {name: 'ready:request'}
main.af6d8eda1550bb1b4419.bundle.js:95 Received postMessage {name: 'ready:request'}
main.af6d8eda1550bb1b4419.bundle.js:95 Unknown post message {name: 'ready:request'}
main.af6d8eda1550bb1b4419.bundle.js:95 Received postMessage {name: 'ready:request'}
main.af6d8eda1550bb1b4419.bundle.js:95 Unknown post message {name: 'ready:request'}
main.af6d8eda1550bb1b4419.bundle.js:95 Received postMessage {name: 'ready:request'}
```

**Comment by canova** [comment]
Hey @sefeng211 Thanks for the bug report!
`ready:request` post message is a message we introduced a few months ago. But since we cache the profiler.firefox.com with a service worker, you might need to update your profiler.firefox.com version to be able to use this properly.

Can you try:
- Visit profiler.firefox.com
- Wait a while, like 10 seconds to see a bar at the top side that tells you that new version of the application is available.
- Click on "Apply and reload" to apply the new update.
- Try to reuse the extension again.

**Comment by sefeng211** [comment]
ah cool, thanks Nazim, that fixes it.
